amazon.email=mochxd@gmail.com
amazon.password=Test@1234
checkout.fullName=Test User
checkout.mobileNumber=01012345678
checkout.addressLine=Nasr
checkout.building=Building 5
checkout.city=Cairo
checkout.district=10
checkout.governorate=Cairo
